version : '3.8'

services:
  db:
    image: postgres:16.1
    environment:
      - "POSTGRES_USER=dev"
      - "POSTGRES_PASSWORD=cm9vdA=="
      - "POSTGRES_DB=docker"
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgres
volumes:
  db_data: